### ISSUE TITLE
Relation: getBounds is broken

### ISSUE THREAD

**Issue by okrische** [oschuen/ballin-happiness#1]
Hello,

getBounds() of Relation does not take over the initial bound of ways. The correct code would be:

```java
				case WAY:
					final Way way = (Way) member.getRef();
					final Bounds wayBounds = way.getBounds();
					if (wayBounds != null) {
						if (bounds == null) {
							bounds = new Bounds(wayBounds);
						} else {
							bounds.increaseBounds(wayBounds);
						}
					}
					break;
```

Are you still interested to improve the code or was it just for showing that it works?

I tried it for the planet file and it took me around half a day on a simple machine with 4G to run through.

I have had some problems with GC excess, though, so i optimized on reading, like, avoiding map construction in node/relation/way, when those will be created on readExternal anyways. I also added bzip2 support through an external lib.

A way to skip objects in the iterator would be very helpful. There are some really heavy objects in OSM (up to 9 levels relations), and i always have to read it completely to be able to skip it and move on with the next one. Which caused me some headache.

In any way, thanks!

**Comment by oschuen** [comment]
You are totally right, this is an issue and your fix is correct. I wrote this code for an article in the German Java Magazin. I don't think I will develop on it much more, since it is doing what I want from it. But of course I will fix this issue in the next few days. I wonder that you found the project at all. 

I did some experiments with other compressions than zip as well, but I found them to slowly, especially without native support.

Thanks for the feedback.
